# fly.toml app configuration file generated for incase on 2024-12-23T08:25:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'incase'
primary_region = 'ams'

[build]
  [build.args]
    GO_VERSION = '1.22'

[env]
  PORT = '8080'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
